# Day 11 - Numpy

NumPy (Numerical Python) মূলত array নিয়ে কাজ করা একটি লাইব্রেরি যা বৈজ্ঞানিক ও গাণিতিক হিসাব নিকাশ করার জন্য ব্যবহার করা হয়।

- **ndarray** (N-dimensional array) → NumPy এর প্রধান অবজেক্ট।
- এটি এক বা একাধিক মাত্রার (1D, 2D, 3D...) ডেটা সংরক্ষণ করতে পারে।
- **একই ডেটা টাইপ** → NumPy অ্যারেতে সব উপাদানের ডেটা টাইপ একই হয় । যেমন সব int বা সব float।
- **দ্রুত গাণিতিক অপারেশন** → বড় ডেটাসেটের ওপর যোগ, গুণ, ভাগ ইত্যাদি খুব দ্রুত করা যায়।
- **কম কোডে বেশি কাজ** → সাধারণ পাইথন লুপ ব্যবহার না করেও অনেক অপারেশন করা যায়।
- পাইথনের list এর চেয়ে অনেক দ্রুত কাজ করে।
- বড় ডেটা সহজে হ্যান্ডেল করা যায়।
- ম্যাথ, স্ট্যাটিসটিকস, মেশিন লার্নিং, ডেটা অ্যানালাইসিসে এইটি অপরিহার্য।

numpy কাজ করে SIMD (Single Instruction, Multiple Data) প্রসেসে    
scaler operation     ________       SIMD operation        
a1+B1=c1 ______________ a1 B1=c1    
a2+B2=c2 ______________ a2+B2=c2    
a3+B3=c3 ______________ a3 B3=c3    

In [ ]:
import numpy as np          # যেহেতু আলাদা লাইব্রেরী,, তাই ইমপোর্ট করে নিতে হয়

l = [1, 2, 3]
n = np.array([1, 2, 3])

print(type(n))

# কেন লিস্ট ব্যবহার না করে numpy ব্যবহার করবো??????
# here is the example

print("miltiply in list : ", l * 5)         # list এর সাথে যদি ৫ গুন করি তাহলে এটা লিস্ট কে ৫ বার মাল্টিপ্লাই করে,, যা ম্যাথম্যাটিকাল হলো না,, অন্যান্য ম্যাথের জন্য ও সেইম

print("multiply in numpy : ", n * 5)        # but তে ৫ গুন করলে এটা প্রতি ইলিমেন্ট এর সাথে ৫ গুন করে,, ম্যাথম্যাটিকাললি আমরা যেটা চাই

l2 = [4, 5, 6]
n2 = np.array([4, 5, 6])

print("plus in list : ", l+l2)
print("plus in numpy : ", n+n2)

<class 'numpy.ndarray'>
miltiply in list :  [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
multiply in numpy :  [ 5 10 15]
plus in list :  [1, 2, 3, 4, 5, 6]
plus in numpy :  [5 7 9]


In [144]:
# 1D array      row
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array      row+column
arr2 = np.array([[1, 2, 3],         
                 [4, 5, 6]])        

# 3D array      row+column+height
arr3 = np.array(
    [[[1, 2, 3], [4, 5, 6]],        
     [[1, 2, 3], [4, 5, 6]],        
     [[1, 2, 3], [4, 5, 6]]]        
)

# Array Attributes
# ndim বলে দেয় অ্যারেটি কয় dimensional এর।
print(arr3.ndim)

# shape বলে দেয় প্রতিটি dimension এ কয়টি উপাদান আছে ,যেমন সারি ও কলাম সংখ্যা।  tuple output dey
print(arr2.shape)
print(arr3.shape)

# size বলে দেয় অ্যারেতে মোট কয়টি উপাদান আছে।
print(arr2.size)
print(arr3.size)

3
(2, 3)
(3, 2, 3)
6
18


### ndarray Data Type
NumPy এর ndarray এ সব element একই type এর হতে হয়।    
যেমন → সবগুলো সংখ্যা হলে int বা float হবে, কিন্তু ভিন্ন টাইপ হলে NumPy সেটিকে এক টাইপে রূপান্তর করে নেয়।

In [24]:
arr = np.array([1, 2, 3])
print(arr.dtype)            

arr = np.array([1.5, 2.9, 3.1])
print(arr.dtype)            

# upcasting == যেহেতু নামপাই এক টাইপের ডেটা নিয়েই কাজ করে তাই সে upcasting করে সব int কে float এ কনভার্ট কেরে ফেলছে,, একই বলে upcasting
arr = np.array([1, 2, 3.1])
print(arr.dtype)            

# এখানেও upcasting করে সবগুলিকে string এ নিয়ে গেছে,, এখানে U মানে unicode string
arr = np.array([1, 2, "6", "hi bro", 3.1])
print(arr.dtype)            


###### উল্লেখ্য ##########

# এখানে ডাটা টাইপের শেষে যে সংখ্যা থাকে তা বিট বুঝায়
# int8 → 8-bit integer value (-128 to 127)
# int16 → 16-bit integer value (-32768 to 32767)
# int32 → 32-bit integer value (-2147483648 to 2147483647)
# int64 → 64-bit integer value (-9223372036854775808 to 9223372036854775807)

int64
float64
float64
<U32


In [ ]:
# change data type
arr = np.array([1, 2, 3], dtype=np.int8)
print(arr.dtype)

arr = arr.astype(np.int32)              # another way to change data type
print(arr.dtype)

# now
# arr = np.array([1, 2, 300], dtype=np.int8)                    # this line will give error,, because int8 can handle up to 127

# arr = np.array([1, 2, "hi",  3.1], dtype=np.float64)          # will error also,, because string cannot convert to float val
arr = np.array([1, 2, "64",  3.1], dtype=np.float64)            # but here will be no error
print(arr)



int8
int32
[ 1.   2.  64.   3.1]


### ndarray creation from Existing data

In [48]:
print("-------------- list --------------")
lst = [1, 3, 5, 7.5, 96, 2.332, 3565.32, 25, 32]
arr = np.array(lst, dtype=np.int32)
print(arr.dtype)

print("-------------- 2D array --------------")
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
arr = np.array(arr2)
arr.astype(np.float64)
print(arr2)
print(type(arr2))
print(arr2.dtype)
print(arr2.shape)
print(arr2.ndim)

print("-------------- Tuple --------------")
# tuple,, nested tuple any thing is convertable as like 2D array
tpl = (2, 1, 4, 5, 9)
arr = np.array(tpl)
print(arr)

print("-------------- Set --------------")
# ndarray direct set কে element/object হিসাবে নিয়ে নেয় so যেহেতু set unordered, তাই একে list() দিয়ে রূপান্তর করে তারপর NumPy অ্যারে বানানো হয়েছে।

st = {10, 20, 30}

arr = np.array(st)      # direct set 1 ta elemnt hy
print(arr)

arr = np.array(list(st))    # list e convert korar por
print(arr)

print("-------------- Dictionary --------------")

dc = {"a": 10, "b": 20, "c": 30}

# Keys থেকে ndarray
arr = np.array(list(dc.keys()))
print(arr)
print(arr.dtype)

# Values থেকে ndarray
arr = np.array(list(dc.values()))
arr = arr.astype(np.int16)
print(arr)
print(arr.dtype)

# Items (key-value pair) থেকে ndarray
arr = np.array(list(dc.items()))
print(arr)
print(arr.dtype)
print(arr.size)

-------------- list --------------
int32
-------------- 2D array --------------
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
-------------- Tuple --------------
[2 1 4 5 9]
-------------- Set --------------
{10, 20, 30}
[10 20 30]
-------------- Dictionary --------------
['a' 'b' 'c']
<U1
[10 20 30]
int16
[['a' '10']
 ['b' '20']
 ['c' '30']]
<U21
6


### ndarray creation from scratch

In [ ]:
arr = np.zeros((2, 5))          # (2,3) মানে ২ সারি ও ৩ কলামের 2D অ্যারে যার সব ভ্যালু 0 হবে
print(arr)

# এখন যদি অন্য কোনো exixting array এর shape ও dtype নিয়ে 0 ওয়ালা নতুন অ্যারে বানাতে চাই তাহলে
arr = np.zeros_like(arr2)
print(arr)

arr = np.ones((2, 3))           # ভ্যালু 1 হবে
print(arr)

arr = np.empty((2, 2))          # কিছু random ভ্যালু নিবে
print(arr)

arr = np.full((3, 3), "x")    # যা খুশি তাই দিবো,, তাতেই ফিলআপ হবে,,  10, 45.6, True, "str ing" (np.inf = for infinity value)
print(arr)


#############    _like   ##############
# আমরা যখন _like ব্যবহার করে অন্য কোনো array এর শেপ নিবো তখন কিন্ত array এর সাথে ঐ শেপ এর ডাটা টাইপ ও চলে আসবে

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1.   2. ]
 [64.   3.1]]
[['x' 'x' 'x']
 ['x' 'x' 'x']
 ['x' 'x' 'x']]
inf


### ndarray generation with random values
অনির্দিষ্ট, এক এক সময় এক এক ভ্যালু

In [114]:
arr = np.random.rand(2, 3)          # 0 থেকে 1 এর মাঝে float/দশমিক সংখ্যা নিয়ে array ‍তৈরী করে
print(arr)

# (start, end, shape)
arr = np.random.randint(1, 10, (2, 3))          # 1 থেকে 10 এর মাঝে int value নিয়ে array ‍তৈরী করে
print(arr)

arr = np.random.uniform(11, 20, (2, 3))         # 11 থেকে 20 এর মাঝে float value নিয়ে array ‍তৈরী করে
print(arr)

print("-------------- 3D --------------")

arr = np.random.uniform(11, 20, (2, 2, 2))         # 11 থেকে 20 এর মাঝে float value নিয়ে 3D array ‍তৈরী করে
print(arr)

[[0.98986899 0.93034704 0.49273714]
 [0.51683237 0.02536431 0.87778954]]
[[4 8 7]
 [4 1 4]]
[[16.19483973 14.91901655 14.72700224]
 [14.46522403 15.0224981  18.16230459]]
-------------- 3D --------------
[[[18.35318879 15.06846706]
  [13.71608683 16.52924226]]

 [[18.08205658 11.74409048]
  [16.36895726 16.14165974]]]


### ndarray creation from range
নির্দিষ্ট, একই ভ্যালু সবসময়

In [130]:
arr = np.arange(1, 10, 1)               # পাইথনের range() ফাংশনের মতো, কিন্তু NumPy অ্যারে রিটার্ন করে
print(arr)

mat = arr.reshape(3, 3)                 # reshape করে একই অ্যারে কে 3×3 ম্যাট্রিক্সে রূপান্তর করা হয়েছে
print(mat)

arr = np.linspace(0, 4, 6)            # নির্দিষ্ট সংখ্যক সমান দূরত্বের মান তৈরি
print(arr)

arr = np.logspace(0, 4, 6, base=2)      # লগ স্কেলে (base অনুযায়ী) মান তৈরি করে।
print(arr)
# [ 1.          1.74110113    3.03143313    5.27803164    9.18958684      16.]
#  2^0              2^08         2^1.6          2^2.4       2^3.2         2^4

# linespace এ যেমন নাম্বার গুলাকে evenly ভাগ করে,, এখানে সেই ভাগ করা নাম্বারকে ২ বেস এর পাওয়া হিসাবে দিয়েছে

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0.  0.8 1.6 2.4 3.2 4. ]
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


### creating diagonal and identity matrix using numpy for linear algebra

In [135]:
# Diagonal Matrix
diagonal_mat = np.diag([1, 2, 3, 4])
print(diagonal_mat)

# Identity Matrix
identity_mat = np.eye(4)
print(identity_mat)

# Custom Identity Matrix
c_i_mat = np.eye(3, 4)
print(c_i_mat)

# Custom Identity Matrix with k parameter
# k = 1 → মূল কর্ণের এক ধাপ উপরে
# k = -1 → দিলে নিচের দিকে সরে যায়
mat = np.eye(3, 4, 1)
print(mat)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Indexing and Slicing


In [148]:
# indexing

print(arr1)
print(arr2)

arr1[2] = 100           # changing value
print(arr1)

arr2[0][2] = 100        # Changing value
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[  1   2 100   4   5]
[[  1   2 100]
 [  4   5   6]]


In [150]:
# slicing
# 1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()         # copy important
arr1[1] = 2
# arr1[1:4] মানে index 1 থেকে 3 পর্যন্ত অংশ নেওয়া।
# .copy() দিলে আলাদা কপি তৈরি হয় (মূল অ্যারেতে পরিবর্তন হলে এতে প্রভাব পড়ে না)।

arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2 100 200]
[  1   2 100   4   5]


In [ ]:
# 2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2) 

#getting a row 

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)

#getting a column 

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion 

portion = arr2[:: , 0:2] 

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


### Advanced Indexing and Iteration
NumPy তে ইনডেক্সিং শুধু সাধারণ সংখ্যা দিয়েই নয় → বরং index এর list, boolean শর্ত, এমনকি লুপ দিয়েও করা যায়। এগুলোকে একসাথে বলা হয় Advanced Indexing।

In [154]:
lst = np.array([10, 20, 30, 40])
values = lst[[0, 3, 1]]

print(values)

# 2D Integer Indexing,,, 2D অ্যারের সারি ও কলাম নির্দিষ্ট করে একাধিক মান একসাথে নেওয়া যায়।
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

print(arr2[[0, 1], 
           [1, 2]])

# Boolean Indexing,, কোনো শর্ত অনুযায়ী মান বেছে নেওয়া
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(arr[arr > 1])

# Boolean শর্ত দিয়ে মান পরিবর্তন করা
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr[arr > 2] = 0
print(arr)

[10 40 20]
[2 6]
[2 3 4 5 6]
[[1 2 0]
 [0 0 0]]


### Iterating Over Arrays

In [156]:
arr3 = np.array([[[1, 2, 3], 
                  [4, 5, 6]], 

                 [[7, 8, 9], 
                  [10, 11, 12]]])

for i in np.nditer(arr3):
    print(i)

# np.nditer() দিয়ে যেকোনো dimension এর অ্যারে থেকে এক এক করে সব মান পাওয়া যায়।
# এটি nested loop ছাড়াই সব মান ঘুরে দেখতে সাহায্য করে।

1
2
3
4
5
6
7
8
9
10
11
12
