# Day 11 - Numpy for more Data Analysis 

### Numpy array manipulation

In [6]:
import numpy as np

# array reshape
# ধরি আমাদের 10X5=50 টি ডাটা দেওয়া আছে। এটাকে আমরা চাইলে 5X10=50 বা 25X2=50 এভাবে reshape করতে পারি। অর্থাৎ ৫০ ডাটা ঠিক রেখে যেভাবে ইচ্ছা সেভাবে reshape করতে পারি।
arr = np.random.randint(1, 100, size = (10, 5))         # Sample 10,, feature 5,, 2D array
print(arr)

[[24 32 50 25 92]
 [55  1 92 51  3]
 [ 6 51 39 45 86]
 [ 7  6  5  5 81]
 [72 41  3 51 23]
 [67 69 35  3 47]
 [92 86 55 37 31]
 [39 43  8 92  7]
 [ 5 49 39 66 94]
 [29 47 18 72 22]]


In [7]:
arr2 = arr.reshape(5, 10)                               # sample 5,, feature 10,, 2D array
print(arr2)

[[24 32 50 25 92 55  1 92 51  3]
 [ 6 51 39 45 86  7  6  5  5 81]
 [72 41  3 51 23 67 69 35  3 47]
 [92 86 55 37 31 39 43  8 92  7]
 [ 5 49 39 66 94 29 47 18 72 22]]


In [8]:
arr3 = arr2.flatten()                                    # sample 1,, feature 50,, 1D array
arr3 = np.ravel(arr2, order="C")                         # row-major (C-style) order,, দুইটা সেইম কাজ করে
print(arr3)

# এখানে ডাটাকে row wise reshape করা হয় ,, অর্থাৎ ১ম row এর শেষ element '21'এর-পর ২য় row এর প্রথম element '94' এসেছে।

[24 32 50 25 92 55  1 92 51  3  6 51 39 45 86  7  6  5  5 81 72 41  3 51
 23 67 69 35  3 47 92 86 55 37 31 39 43  8 92  7  5 49 39 66 94 29 47 18
 72 22]


In [9]:
arr4 = np.ravel(arr2, order="F")                        # F means (Fortran-style) order
print(arr4)

# এখানে ডাটাকে column wise reshape করা হয় ,, অর্থাৎ ১ম column এর শেষ element '68'এর-পর ২য় column এর প্রথম element '47' এসেছে।

[24  6 72 92  5 32 51 41 86 49 50 39  3 55 39 25 45 51 37 66 92 86 23 31
 94 55  7 67 39 29  1  6 69 43 47 92  5 35  8 18 51  5  3 92 72  3 81 47
  7 22]


### array concatenation
দুইটা ndarray জয়েন/একত্র করার মাধ্যম

In [10]:
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(11, 20, (2, 3))

# concatenate এর শর্ত,,
# Row wise concatenate করার সময় ২ array এর column size সেইম হতে হবে।
# Column wise concatenate করার সময় ২ array এর row size সেইম হতে হবে।

In [11]:
con_row = np.concatenate((a, b), axis=0)            # row wise concatenate,, will add row bellow
con_col = np.concatenate((a, b), axis=1)            # column wise concatenate,, will add column beside

print(con_row)
print(con_col)

[[ 4  6  7]
 [ 1  4  2]
 [12 13 13]
 [19 17 15]]
[[ 4  6  7 12 13 13]
 [ 1  4  2 19 17 15]]


### Transpose
convert row into column

In [12]:
transpose = b.T
print(transpose)

[[12 19]
 [13 17]
 [13 15]]


In [13]:
# array split -> যেভাবে ইচ্ছা সেভাবে

a = np.random.randint(1, 10, size=(10,))
print(a)
splitted_array = np.array_split(a, 3)
print(splitted_array)

# split -> equal division
b = np.random.randint(1, 10, size=(9,))
print(b)
eq_splitted_array = np.split(b, 3)
print(eq_splitted_array)

[3 9 9 4 5 9 8 6 1 8]
[array([3, 9, 9, 4], dtype=int32), array([5, 9, 8], dtype=int32), array([6, 1, 8], dtype=int32)]
[7 7 9 3 1 5 1 3 6]
[array([7, 7, 9], dtype=int32), array([3, 1, 5], dtype=int32), array([1, 3, 6], dtype=int32)]


### arithmetic operator and mathematical functions
https://numpy.org/doc/stable/reference/routines.math.html

In [14]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([60, 70, 80, 90, 100])

# add = x+y
add = np.add(x,y)
print(add)

# sub = y-x
sub = np.subtract(y,x)
print(sub)

# mul = x*y
mul = np.multiply(x,y)
print(mul)

# div = y/x
div = np.divide(y,x)
print(div)

# mod = y%x
mod = np.mod(y,x)
print(mod)

# pw = x**2
pw = np.power(x, 2)
print(pw)

# sum of all value in x
sm = np.sum(x)
print(sm)

# cumulative sum
cuml_sm = np.cumulative_sum(x)
print(cuml_sm)

[ 70  90 110 130 150]
[50 50 50 50 50]
[ 600 1400 2400 3600 5000]
[6.         3.5        2.66666667 2.25       2.        ]
[ 0 10 20 10  0]
[ 100  400  900 1600 2500]
150
[ 10  30  60 100 150]


### trigonometry

In [15]:
# sin, cos, tan takes value in radian
sin_val = np.sin(10)
print(sin_val)

x = np.array([0, 30, 45, 60, 90, ])          # eikhane value guli radian e ache

sin_arr = np.sin(x)                          # x array er shb elemnt er sin value
print(sin_arr)
# np.arcsin()

cos_val = np.cos(x)
print(cos_val)
# np.arccos

tan_val = np.tan(x)
print(tan_val)
# np.arctan


# lets convert radian value to degree

deg_conv = np.rad2deg(x)
print(deg_conv)

# to get degree to radian value,, we have to use deg2rad()

-0.5440211108893698
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
[   0.         1718.87338539 2578.31007809 3437.74677078 5156.62015618]


### logarithms

In [16]:
x = np.array([10, 8, 16, 100])
base_10_log = np.log10(x)
print(base_10_log)              # বাংলায় বললে,, log10(x) মানে x এর value কে 10 দিয়ে কত বার ভাগ করা যায় সেটাই আউটপুট দেয়


base_2_log = np.log2(x)
print(base_2_log)               # বাংলায় বললে,, log2(x) মানে x এর value কে 2 দিয়ে কত বার ভাগ করা যায় সেটাই আউটপুট দেয়


sqrt = np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


### Numpy Broad Casting

Broadcasting numpy এর এমন একটা প্রসেস বা টাস্ক যেখানে সে অটোমেটিক, scelar data কে strech করে array এর সাথে calculation করে   


In [17]:
x = np.array([10, 20, 30, 40, 50])
print(x+2)

# এখানে x = 10, 20, 30, 40, 50 ,, আমরা যখন x+2 লিখছি তখন এটা ভেতরে ভেতরে 2, 2, 2, 2, 2 এর একটা array এর মতো তৈরী করে এবং 10+2, 20+2, 30+2, 40+2, 50+2 করে আউটপুট দেয়,, this is broadcasting


# rulings = columns er size and vector er size same hote hobe

matrix = np.array([[10, 20, 30], [30, 40, 50]])
vector = np.array([1, 2, 3])
result = matrix + vector
print(result)

[12 22 32 42 52]
[[11 22 33]
 [31 42 53]]


### Logical functions

In [18]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([10, 8, 16, 100])
y = np.array([2, 3, 16, 5])

greater_than = x > y
print(greater_than)

equal = x == y
print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


### sorting

In [19]:
x = np.random.randint(1, 20, (1, 5))

In [20]:
# inplace       এখানে সর্ট করার পরে array elements এর index/প্লেস ই চেঞ্জ হয়ে যায়,, ফলে আগের array আর ফেরত পাওয়া যায় না
z = x.copy()
print(z)
z.sort()
print(z)


# copy sorting      এখানে সর্ট করার পরেও আগের array অক্ষত থাকে
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)


# 2d array sorting
mat = np.array([[10, 3, 5], [8, 4, 9]])

# horizon axis = 1

hor_sort = np.sort(mat, axis=1)
print(hor_sort)

# vertical axis = 0
vert_sort = np.sort(mat, axis=0)
print(vert_sort)

[[10 14  1 12 16]]
[[ 1 10 12 14 16]]
[[10 14  1 12 16]]
[[ 1 10 12 14 16]]
[[10 14  1 12 16]]
[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


### searching
array te kono value ache kina, thakle kon index e ache,, koyta ache,, etc ber kore

In [21]:
x = np.array([5, 9, 8, 13, 2, 25])

index = np.where(x == 8)               # returns index
print(index)

# np.where( condition , x , y ) if true keep x , otherwise replace with y
arr = np.where(x > 8, x, 0)            # returns array
print(arr)

index = np.where(mat > 8)              # returns index
print(index)

arr = np.where(mat > 8, mat, 0)        # returns array
print(arr)

x = np.array([10, 100, 8, 16, 100])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

(array([2]),)
[ 0  9  0 13  0 25]
(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]
1
2


### counting in ndarray and unique values

In [22]:
a = np.random.randint(1, 100, size=(100,))
print(a)

[70 39 47 83  5 60 76 93 22 80 74  3 71 98  5 20 34 33  8 66 75 96 10 83
 27 54 40 79 26 60 56 25 58 96 98 74 23 31 80 26 52 68 29 76 90 54 73 72
 26 57 40 12 13 57 80 72 37 59  4 91 68  5 74 57 76 68 16  7 45 96 94 34
 98 62 71 74 93 86 92 84 87 25 18 52 81 94 96 51 41 13 87 77 10 78 89 21
 35 36 53  9]


In [23]:
value_great_than_60 = np.count_nonzero(a > 60)
value_less_than_60 = np.count_nonzero(a < 60)
value_equal_60 = np.count_nonzero(a == 60)
value_not_equal_60 = np.count_nonzero(a != 60)
print(value_great_than_60)
print(value_less_than_60)
print(value_equal_60)
print(value_not_equal_60)


# find only unique values from the array
unique_value= np.unique(a)

# find unique values with counting their repetition number from the array
unique_value, count = np.unique(a, return_counts=True)

print(unique_value)
print(count)

47
51
2
98
[ 3  4  5  7  8  9 10 12 13 16 18 20 21 22 23 25 26 27 29 31 33 34 35 36
 37 39 40 41 45 47 51 52 53 54 56 57 58 59 60 62 66 68 70 71 72 73 74 75
 76 77 78 79 80 81 83 84 86 87 89 90 91 92 93 94 96 98]
[1 1 3 1 1 1 2 1 2 1 1 1 1 1 1 2 3 1 1 1 1 2 1 1 1 1 2 1 1 1 1 2 1 2 1 3 1
 1 2 1 1 3 1 2 2 1 4 1 3 1 1 1 3 1 2 1 1 2 1 1 1 1 2 2 4 3]


### statistical function

In [ ]:
# data load

data = np.genfromtxt("D12-1_student_scores.csv", delimiter=",", skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [25]:
# statistics
math_marks = data[::, :1]                       # eikhane math marks er column ke alada kora hoyeche

print(math_marks.T)                             # output ekta lomba column,, ty transpose kore row banano hoyeche

max_math_marks = np.max(math_marks)             # max marks ber kora hocche
print(max_math_marks)

min_math_marks = np.min(math_marks)             # min
print(min_math_marks)

average_math_marks = np.mean(math_marks)        # average
print(average_math_marks)

median_math_marks = np.median(math_marks)       # median
print(median_math_marks)

std_math_marks = np.std(math_marks)             # standard deviation
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


### linear algebra

In [31]:
A = np.array([[1, 2, 3], [4, 5, 6]])

B = np.array([[7, 8], [9, 10], [11, 12]])

# a er column and b er row same length hote hobe
dot_product = np.dot(A, B)
print(dot_product)


# trace
print(np.trace(B))


[[ 58  64]
 [139 154]]
17


In [34]:
sq_mat = np.array([[1, 20, 3], 
                   [4, 5, 6], 
                   [17, 8, 9]])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)
## https://www.notion.so/Numpy-Array-Matrix-Example-293ac54e82a08063865ec988b6be0bc3
print(rank_sq)

1158.0000000000005
3
