**Email Address: nurularefinnabil@gmail.com**

In [27]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


**Q1.** Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.

In [29]:
age = np.array(ages)
print(age)
print(age.dtype)
print(age.ndim)
print(age.shape)
print(age.size)

slry = np.array(salaries)
print(slry)
print(slry.dtype)
print(slry.ndim)
print(slry.shape)
print(slry.size)

[56 46 32 25 38 56 36 40 28 28]
int64
1
(10,)
10
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10


**Q2.** Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.


In [30]:
highst_sl = np.max(salary)
print("Highest salary :", highst_sl)
lwst_sl = np.min(salary)
print("Lowest salary :", lwst_sl)

avrg_sl = np.mean(salaries)
print("Average salery :",avrg_sl)
avrg_age = np.mean(ages)
print("Average age :",avrg_age)

Highest salary : 89735
Lowest salary : 30769
Average salery : 57446.9
Average age : 38.5


**Q3.** From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.


In [38]:
grtr_30 = age[age>30]
print(grtr_30)
print(np.count_nonzero(grtr_30))

[56 46 32 38 56 36 40]
7


**Q4.** Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

**Q5.** Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.

**Q6.** Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().

**Q7.** Display only the id, age, and salary columns. Then show the last 3 rows using tail().


**Q8.** Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.

**Q9.** Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.

**Q10.** Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.